# Generated by Django 3.2.12 on 2022-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('motdepasse', models.CharField(max_length=25, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
