# Generated by Django 2.2.8 on 2022-08-12 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSysteme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleConsultation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmbauche', models.DateField()),
                ('dateResiliation', models.DateField()),
                ('statut', models.BooleanField()),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleExamen', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Masse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleMedicament', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOrdonnance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='policeAssurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('taux', models.IntegerField()),
                ('datePriseEffet', models.DateField()),
                ('dateFin', models.DateField()),
                ('statutModification', models.BooleanField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellePrestation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Quantite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='voieAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=40)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Souscripteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='centreDeSoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('dateNaiss', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=40, null=True)),
                ('taille', models.FloatField(max_length=4, null=True)),
                ('masse', models.FloatField(max_length=6, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('defautSante', models.CharField(max_length=40, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('ayantDroit', models.BooleanField()),
                ('statut', models.BooleanField()),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('longitude', models.FloatField(max_length=20, null=True)),
                ('latitude', models.FloatField(max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSancfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('admin_systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.AdminSysteme')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentLaboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
