# Generated by Django 2.2.8 on 2022-08-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsancfis',
            name='admin_systeme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.AdminSysteme'),
        ),
    ]
