# Generated by Django 3.2.12 on 2022-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsysteme',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
