# Generated by Django 3.2.12 on 2022-08-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_alter_adminsysteme_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsysteme',
            name='pays',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='agentsSancfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('motdepasse', models.CharField(max_length=25, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_systeme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.adminsysteme')),
            ],
        ),
    ]
