# Generated by Django 2.2.8 on 2022-08-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_auto_20220812_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsancfis',
            name='admin_systeme',
        ),
    ]
