# Generated by Django 3.2.12 on 2022-08-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_auto_20220805_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentssancfis',
            name='admin_systeme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.adminsysteme'),
        ),
    ]
